"""initial schema - 18 bang tu ERD

Revision ID: 02f963b388c8
Revises: 
Create Date: 2026-08-22 15:52:48.335534

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '02f963b388c8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('source', sa.String(length=255), nullable=True),
    sa.Column('current_classification', sa.Enum('A', 'B', 'C', name='customerclassification', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('division',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('personnel_cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff_group', sa.Enum('LEADERSHIP', 'MANAGEMENT', 'FRONTLINE', 'MIDDLE', 'BACKEND', name='staffgroup', native_enum=False, length=20), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('service',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('supplier',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('budget',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_budget_division_id'), 'budget', ['division_id'], unique=False)
    op.create_table('cost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cost_division_id'), 'cost', ['division_id'], unique=False)
    op.create_table('customer_classification_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('classification', sa.Enum('A', 'B', 'C', name='customerclassification', native_enum=False), nullable=False),
    sa.Column('snapshot_date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customer_classification_history_customer_id'), 'customer_classification_history', ['customer_id'], unique=False)
    op.create_table('department',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_department_division_id'), 'department', ['division_id'], unique=False)
    op.create_table('employee',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('staff_group', sa.Enum('LEADERSHIP', 'MANAGEMENT', 'FRONTLINE', 'MIDDLE', 'BACKEND', name='staffgroup', native_enum=False, length=20), nullable=False),
    sa.Column('position', sa.String(length=255), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_employee_department_id'), 'employee', ['department_id'], unique=False)
    op.create_table('debt',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('division_id', sa.Integer(), nullable=False),
    sa.Column('department_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('due_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['department_id'], ['department.id'], ),
    sa.ForeignKeyConstraint(['division_id'], ['division.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_debt_customer_id'), 'debt', ['customer_id'], unique=False)
    op.create_index(op.f('ix_debt_department_id'), 'debt', ['department_id'], unique=False)
    op.create_index(op.f('ix_debt_division_id'), 'debt', ['division_id'], unique=False)
    op.create_index(op.f('ix_debt_employee_id'), 'debt', ['employee_id'], unique=False)
    op.create_table('sales_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('order_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('revenue', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('order_cost', sa.Numeric(precision=18, scale=2), nullable=False),
    sa.Column('invoice_status', sa.String(length=50), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sales_order_customer_id'), 'sales_order', ['customer_id'], unique=False)
    op.create_index(op.f('ix_sales_order_employee_id'), 'sales_order', ['employee_id'], unique=False)
    op.create_index(op.f('ix_sales_order_service_id'), 'sales_order', ['service_id'], unique=False)
    op.create_table('supplier_evaluation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('supplier_id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('period', sa.Date(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.ForeignKeyConstraint(['supplier_id'], ['supplier.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_supplier_evaluation_employee_id'), 'supplier_evaluation', ['employee_id'], unique=False)
    op.create_index(op.f('ix_supplier_evaluation_service_id'), 'supplier_evaluation', ['service_id'], unique=False)
    op.create_index(op.f('ix_supplier_evaluation_supplier_id'), 'supplier_evaluation', ['supplier_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=100), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'MANAGER', 'USER', name='userrole', native_enum=False, length=20), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_index(op.f('ix_users_employee_id'), 'users', ['employee_id'], unique=False)
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=50), nullable=False),
    sa.Column('table_name', sa.String(length=100), nullable=False),
    sa.Column('record_id', sa.Integer(), nullable=False),
    sa.Column('changed_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('old_value', sa.Text(), nullable=True),
    sa.Column('new_value', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_user_id'), 'audit_log', ['user_id'], unique=False)
    op.create_table('import_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imported_by', sa.Integer(), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('import_type', sa.String(length=100), nullable=False),
    sa.Column('row_count', sa.Integer(), nullable=False),
    sa.Column('error_count', sa.Integer(), nullable=False),
    sa.Column('imported_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['imported_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_import_history_imported_by'), 'import_history', ['imported_by'], unique=False)
    op.create_table('login_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('login_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_history_user_id'), 'login_history', ['user_id'], unique=False)
    op.create_table('price_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=True),
    sa.Column('request_date', sa.Date(), nullable=False),
    sa.Column('is_won', sa.Boolean(), nullable=False),
    sa.Column('sales_order_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['employee.id'], ),
    sa.ForeignKeyConstraint(['sales_order_id'], ['sales_order.id'], ),
    sa.ForeignKeyConstraint(['service_id'], ['service.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_price_request_customer_id'), 'price_request', ['customer_id'], unique=False)
    op.create_index(op.f('ix_price_request_employee_id'), 'price_request', ['employee_id'], unique=False)
    op.create_index(op.f('ix_price_request_sales_order_id'), 'price_request', ['sales_order_id'], unique=False)
    op.create_index(op.f('ix_price_request_service_id'), 'price_request', ['service_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # SỬA (xem docs/teaching-notes/huong-dan, bước 4.1): bản auto-generate
    # gốc chỉ có drop_index/drop_table, KHÔNG có drop_constraint nào cho FK
    # -> MySQL báo lỗi 1553 "needed in a foreign key constraint" vì bị xoá
    # index trong khi FK constraint (không đặt name= tường minh ở upgrade(),
    # nên MySQL tự sinh tên <table>_ibfk_N) vẫn còn tham chiếu đúng index đó.
    # Đã thêm đúng 1 op.drop_constraint(...) NGAY TRƯỚC mỗi op.drop_index(...)
    # thao tác trên cột có FK — tên constraint lấy từ information_schema của
    # DB "lacco" đang chạy thật (khớp thứ tự sa.ForeignKeyConstraint(...) ở
    # upgrade() cho từng bảng). upgrade() và các lệnh drop_table/drop_index
    # khác giữ nguyên, không đổi.
    op.drop_constraint('price_request_ibfk_4', 'price_request', type_='foreignkey')
    op.drop_index(op.f('ix_price_request_service_id'), table_name='price_request')
    op.drop_constraint('price_request_ibfk_3', 'price_request', type_='foreignkey')
    op.drop_index(op.f('ix_price_request_sales_order_id'), table_name='price_request')
    op.drop_constraint('price_request_ibfk_2', 'price_request', type_='foreignkey')
    op.drop_index(op.f('ix_price_request_employee_id'), table_name='price_request')
    op.drop_constraint('price_request_ibfk_1', 'price_request', type_='foreignkey')
    op.drop_index(op.f('ix_price_request_customer_id'), table_name='price_request')
    op.drop_table('price_request')
    op.drop_constraint('login_history_ibfk_1', 'login_history', type_='foreignkey')
    op.drop_index(op.f('ix_login_history_user_id'), table_name='login_history')
    op.drop_table('login_history')
    op.drop_constraint('import_history_ibfk_1', 'import_history', type_='foreignkey')
    op.drop_index(op.f('ix_import_history_imported_by'), table_name='import_history')
    op.drop_table('import_history')
    op.drop_constraint('audit_log_ibfk_1', 'audit_log', type_='foreignkey')
    op.drop_index(op.f('ix_audit_log_user_id'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_constraint('users_ibfk_1', 'users', type_='foreignkey')
    op.drop_index(op.f('ix_users_employee_id'), table_name='users')
    op.drop_table('users')
    op.drop_constraint('supplier_evaluation_ibfk_3', 'supplier_evaluation', type_='foreignkey')
    op.drop_index(op.f('ix_supplier_evaluation_supplier_id'), table_name='supplier_evaluation')
    op.drop_constraint('supplier_evaluation_ibfk_2', 'supplier_evaluation', type_='foreignkey')
    op.drop_index(op.f('ix_supplier_evaluation_service_id'), table_name='supplier_evaluation')
    op.drop_constraint('supplier_evaluation_ibfk_1', 'supplier_evaluation', type_='foreignkey')
    op.drop_index(op.f('ix_supplier_evaluation_employee_id'), table_name='supplier_evaluation')
    op.drop_table('supplier_evaluation')
    op.drop_constraint('sales_order_ibfk_3', 'sales_order', type_='foreignkey')
    op.drop_index(op.f('ix_sales_order_service_id'), table_name='sales_order')
    op.drop_constraint('sales_order_ibfk_2', 'sales_order', type_='foreignkey')
    op.drop_index(op.f('ix_sales_order_employee_id'), table_name='sales_order')
    op.drop_constraint('sales_order_ibfk_1', 'sales_order', type_='foreignkey')
    op.drop_index(op.f('ix_sales_order_customer_id'), table_name='sales_order')
    op.drop_table('sales_order')
    op.drop_constraint('debt_ibfk_4', 'debt', type_='foreignkey')
    op.drop_index(op.f('ix_debt_employee_id'), table_name='debt')
    op.drop_constraint('debt_ibfk_3', 'debt', type_='foreignkey')
    op.drop_index(op.f('ix_debt_division_id'), table_name='debt')
    op.drop_constraint('debt_ibfk_2', 'debt', type_='foreignkey')
    op.drop_index(op.f('ix_debt_department_id'), table_name='debt')
    op.drop_constraint('debt_ibfk_1', 'debt', type_='foreignkey')
    op.drop_index(op.f('ix_debt_customer_id'), table_name='debt')
    op.drop_table('debt')
    op.drop_constraint('employee_ibfk_1', 'employee', type_='foreignkey')
    op.drop_index(op.f('ix_employee_department_id'), table_name='employee')
    op.drop_table('employee')
    op.drop_constraint('department_ibfk_1', 'department', type_='foreignkey')
    op.drop_index(op.f('ix_department_division_id'), table_name='department')
    op.drop_table('department')
    op.drop_constraint('customer_classification_history_ibfk_1', 'customer_classification_history', type_='foreignkey')
    op.drop_index(op.f('ix_customer_classification_history_customer_id'), table_name='customer_classification_history')
    op.drop_table('customer_classification_history')
    op.drop_constraint('cost_ibfk_1', 'cost', type_='foreignkey')
    op.drop_index(op.f('ix_cost_division_id'), table_name='cost')
    op.drop_table('cost')
    op.drop_constraint('budget_ibfk_1', 'budget', type_='foreignkey')
    op.drop_index(op.f('ix_budget_division_id'), table_name='budget')
    op.drop_table('budget')
    op.drop_table('supplier')
    op.drop_table('service')
    op.drop_table('personnel_cost')
    op.drop_table('division')
    op.drop_table('customer')
    # ### end Alembic commands ###
